name: Rust

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.94.1

      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets -- -D clippy::all

  build_and_release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: check
    name: Build and Release
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.94.1
        with:
          components: clippy, rustfmt

      - name: setup
        run: |
          cargo install agb-gbafix

      - name: build
        run: cargo build --release

      - name: build gba
        run: agb-gbafix target/thumbv4t-none-eabi/release/game -o gbarcade_v0.1.3.gba -tGBArcade -cAGAE -mEB -r13

      - uses: softprops/action-gh-release@v1
        with:
          files: gbarcade_v0.1.3.gba
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}